---
version: '3.5'
services:
  python-app:
    build: .
    env_file:
      - ./.env_python_talk

    container_name: pythontalk

    volumes:
      - ./persistent/pythontalk/data/:/code/data/

    restart: unless-stopped

    networks:
      - default
